// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GesApprovisionnement.Migrations
{
    [DbContext(typeof(GesApproDbContext))]
    [Migration("20251204120840_FixturesInit3")]
    partial class FixturesInit3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.ApproArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproId")
                        .HasColumnType("integer");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApproId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ApproArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApproId = 1,
                            ArticleId = 1,
                            Montant = 300000m,
                            Quantite = 200
                        },
                        new
                        {
                            Id = 2,
                            ApproId = 1,
                            ArticleId = 2,
                            Montant = 50000m,
                            Quantite = 100
                        },
                        new
                        {
                            Id = 3,
                            ApproId = 2,
                            ArticleId = 4,
                            Montant = 15000m,
                            Quantite = 50
                        },
                        new
                        {
                            Id = 4,
                            ApproId = 3,
                            ArticleId = 3,
                            Montant = 30000m,
                            Quantite = 300
                        },
                        new
                        {
                            Id = 5,
                            ApproId = 3,
                            ArticleId = 1,
                            Montant = 225000m,
                            Quantite = 150
                        });
                });

            modelBuilder.Entity("Models.Approvisionnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaires")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateApprovisionnement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("Approvisionnements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Commentaires = "",
                            DateApprovisionnement = new DateTime(2023, 4, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            FournisseurId = 1,
                            MontantTotal = 0m,
                            Reference = "APP-2023-001",
                            Statut = 0
                        },
                        new
                        {
                            Id = 2,
                            Commentaires = "",
                            DateApprovisionnement = new DateTime(2023, 4, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            FournisseurId = 2,
                            MontantTotal = 0m,
                            Reference = "APP-2023-002",
                            Statut = 0
                        },
                        new
                        {
                            Id = 3,
                            Commentaires = "",
                            DateApprovisionnement = new DateTime(2023, 4, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            FournisseurId = 3,
                            MontantTotal = 0m,
                            Reference = "APP-2023-003",
                            Statut = 1
                        });
                });

            modelBuilder.Entity("Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Tissu Coton",
                            PrixUnitaire = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Fil Polyester",
                            PrixUnitaire = 500m
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Boutons Métal",
                            PrixUnitaire = 100m
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Fermeture Éclair",
                            PrixUnitaire = 300m
                        });
                });

            modelBuilder.Entity("Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Textiles Dakar SARL",
                            Tel = "77 123 45 67"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Mercerie Centrale",
                            Tel = "78 222 33 44"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Tissus Premium",
                            Tel = "76 987 65 43"
                        });
                });

            modelBuilder.Entity("Models.ApproArticle", b =>
                {
                    b.HasOne("Models.Approvisionnement", "Appro")
                        .WithMany("ApproArticles")
                        .HasForeignKey("ApproId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Article", "Article")
                        .WithMany("ApproArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appro");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Models.Approvisionnement", b =>
                {
                    b.HasOne("Models.Fournisseur", "Fournisseur")
                        .WithMany("approvisionnements")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("Models.Approvisionnement", b =>
                {
                    b.Navigation("ApproArticles");
                });

            modelBuilder.Entity("Models.Article", b =>
                {
                    b.Navigation("ApproArticles");
                });

            modelBuilder.Entity("Models.Fournisseur", b =>
                {
                    b.Navigation("approvisionnements");
                });
#pragma warning restore 612, 618
        }
    }
}
